const schools = [
  {
    name: 'Cape Coral Academy',
    street: '7777 Hillcrest Road',
    city: 'Palm Beach',
    state: 'FL',
    zip: 32951,
    website: 'http://cca.example.com',
  },
  {
    name: 'Deer Valley High School',
    street: '9583 Elm Ave.',
    city: 'Warren',
    state: 'OR',
    zip: 17200,
    website: 'http://dvhs.example.com',
  },
  {
    name: 'Elk Creek High School',
    street: '642 Lilac St.',
    city: 'Portsmouth',
    state: 'ID',
    zip: 25398,
    website: null,
  },
  {
    name: 'Horizon Academy',
    street: '5653 Skyline Dr.',
    city: 'Sunset',
    state: 'MI',
    zip: 56192,
    website: null,
  },
  {
    name: 'Laguna Bay High School',
    street: '3 Bayview Dr.',
    city: 'Newport Beach',
    state: 'CA',
    zip: 83194,
    website: 'http://lbhs.example.com',
  },
  {
    name: 'Lone Oak High School',
    street: '4147 Solitary St.',
    city: 'My City',
    state: 'VT',
    zip: 78894,
    website: 'http://lohs.example.com',
  },
  {
    name: 'Lincoln High School',
    street: '1865 Lincoln St.',
    city: 'Saint Marys',
    state: 'NE',
    zip: 80600,
    website: null,
  },
  {
    name: 'Maple Valley High School',
    street: '11 Acer Dr.',
    city: 'Tamaqua',
    state: 'NY',
    zip: 22178,
    website: 'http://mvhs.example.com',
  },
  {
    name: 'Meadow Ridge Technical School',
    street: '3258 W. 35th Ave.',
    city: 'Lakeland',
    state: 'TX',
    zip: 42867,
    website: 'http://mrts.example.com',
  },
  {
    name: 'Sunny Coast High School',
    street: '2020 Clear Sky Dr.',
    city: 'Orange',
    state: 'GA',
    zip: 69293,
    website: 'http://schs.example.com',
  },
]

export default schools
